name: Build Next.JS APP

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: Deploy
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.0
      - name: Install Dependencies
        run: npm Install
      - name: Build Next.JS
        run: npm run build
      - name: Deploy App
        run: echo "Deploy App...."
      
